import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { AppBar } from "@/components/AppBar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/utils/cn";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Smart Insurance Portal Sample",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("min-h-dvh bg-gray-200 antialiased dark:bg-gray-900", geistSans.variable, geistMono.variable)}
      >
        <ThemeProvider>
          <AppBar />
          <main className="pt-24">{children}</main>
          <ToastContainer position="top-right" newestOnTop closeOnClick autoClose={3000} />
        </ThemeProvider>
      </body>
    </html>
  );
}
